### ISSUE TITLE
run the web server not work 

### ISSUE THREAD

**Issue by tchernobyl** [hookTracker/timeTrackerHook#6]
@gdalyy , this issue appeared after merging with authentication brache 
I got this error when I run npm run ng:serve:web

> ERROR in ./node_modules/electron/index.js
> Module not found: Error: Can't resolve 'fs' in '/Users/tchernobyl/Codnect/timeTrackerHook2/node_modules/electron'

can you see it please

**Comment by gdalyy** [comment]
Resolved :heavy_check_mark:

Details : 

this error appears when using 

`const {ipcRenderer} = require('electron');`

in angular component , instead i'm now using `ipcRenderer` from `ElectronService` and this resolves this bug.

[Check here](https://github.com/hookTracker/timeTrackerHook/blob/3223ee9de93a83a4f9feaf8455cffae0174c89b9/src/app/authentication/authentication.component.ts#L50) .
